export const authors = [
  { id: 1, name: "Şeyhi", information: "" },
  { id: 2, name: "Ali Şair Nevai", information: "" },
  { id: 3, name: "Şeyh Galip", information: "" },
  { id: 4, name: "Nabi", information: "" },
  { id: 5, name: "Yunus Emre", information: "" },
  { id: 6, name: "Fuzuli", information: "" },
  { id: 7, name: "Baki", information: "" },
  { id: 8, name: "Nedim", information: "" },
  { id: 9, name: "Namik Kemal", information: "" },
  { id: 10, name: "Recaizade Mahmut Ekrem", information: "" },
  { id: 11, name: "Semipaşazade Sezai", information: "" },
  { id: 12, name: "Nabizade Nazim", information: "" },
  { id: 13, name: "Şemşettin Sami", information: "" },
  { id: 14, name: "Ahmet Mithat Efendi", information: "" },
  { id: 15, name: "Şinasi", information: "" },
  { id: 16, name: "Halit Ziya Uşakligil", information: "" },
  { id: 17, name: "Hüseyin Rahmi Gürpinar", information: "" },
  { id: 18, name: "Mehmet Rauf", information: "" },
  { id: 19, name: "Hüseyin Cahit Yalçin", information: "" },
  { id: 20, name: "Yakup Kadri Karaosmanoğlu", information: "" },
  { id: 21, name: "Halide Edip Adivar", information: "" },
  { id: 22, name: "Reşat Nuri Gültekin", information: "" },
  { id: 23, name: "Ömer Seyfettin", information: "" },
  { id: 24, name: "Haldun Taner", information: "" },
  { id: 25, name: "Ahmet Hamdi Tanpinar", information: "" },
  { id: 26, name: "Oguz Atay", information: "" },
  { id: 27, name: "İnci Aral", information: "" },
  { id: 28, name: "Yusuf Atilgan", information: "" },
];

export const books = [
  { id: 1, name: "Harname", descripton: "", summary: "", image: "", kind_genre: "", language: "", period_id: 1 },
  { id: 2, name: "Harname", descripton: "", summary: "", image: "", kind_genre: "", language: "", period_id: 1 },
  { id: 3, name: "Harname", descripton: "", summary: "", image: "", kind_genre: "", language: "", period_id: 1 },
  { id: 4, name: "Harname", descripton: "", summary: "", image: "", kind_genre: "", language: "", period_id: 1 },
  { id: 5, name: "Harname", descripton: "", summary: "", image: "", kind_genre: "", language: "", period_id: 1 },
  { id: 6, name: "Harname", descripton: "", summary: "", image: "", kind_genre: "", language: "", period_id: 1 },
  { id: 7, name: "Harname", descripton: "", summary: "", image: "", kind_genre: "", language: "", period_id: 1 },
];
